// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcmgr/v1/micro/dcmgr.proto

package dcmgr

import (
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DashBoardRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashBoardRequest) Reset()         { *m = DashBoardRequest{} }
func (m *DashBoardRequest) String() string { return proto.CompactTextString(m) }
func (*DashBoardRequest) ProtoMessage()    {}
func (*DashBoardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{0}
}

func (m *DashBoardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashBoardRequest.Unmarshal(m, b)
}
func (m *DashBoardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashBoardRequest.Marshal(b, m, deterministic)
}
func (m *DashBoardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashBoardRequest.Merge(m, src)
}
func (m *DashBoardRequest) XXX_Size() int {
	return xxx_messageInfo_DashBoardRequest.Size(m)
}
func (m *DashBoardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DashBoardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DashBoardRequest proto.InternalMessageInfo

func (m *DashBoardRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DashBoardResponse struct {
	TotalIncome          int32     `protobuf:"varint,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	CurrentUsage         *Usage    `protobuf:"bytes,2,opt,name=current_usage,json=currentUsage,proto3" json:"current_usage,omitempty"`
	Week                 []*Income `protobuf:"bytes,3,rep,name=week,proto3" json:"week,omitempty"`
	Month                []*Income `protobuf:"bytes,4,rep,name=month,proto3" json:"month,omitempty"`
	Year                 []*Income `protobuf:"bytes,5,rep,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DashBoardResponse) Reset()         { *m = DashBoardResponse{} }
func (m *DashBoardResponse) String() string { return proto.CompactTextString(m) }
func (*DashBoardResponse) ProtoMessage()    {}
func (*DashBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{1}
}

func (m *DashBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashBoardResponse.Unmarshal(m, b)
}
func (m *DashBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashBoardResponse.Marshal(b, m, deterministic)
}
func (m *DashBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashBoardResponse.Merge(m, src)
}
func (m *DashBoardResponse) XXX_Size() int {
	return xxx_messageInfo_DashBoardResponse.Size(m)
}
func (m *DashBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DashBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DashBoardResponse proto.InternalMessageInfo

func (m *DashBoardResponse) GetTotalIncome() int32 {
	if m != nil {
		return m.TotalIncome
	}
	return 0
}

func (m *DashBoardResponse) GetCurrentUsage() *Usage {
	if m != nil {
		return m.CurrentUsage
	}
	return nil
}

func (m *DashBoardResponse) GetWeek() []*Income {
	if m != nil {
		return m.Week
	}
	return nil
}

func (m *DashBoardResponse) GetMonth() []*Income {
	if m != nil {
		return m.Month
	}
	return nil
}

func (m *DashBoardResponse) GetYear() []*Income {
	if m != nil {
		return m.Year
	}
	return nil
}

type Income struct {
	Income               int32                `protobuf:"varint,1,opt,name=income,proto3" json:"income,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Usage                *Usage               `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Income) Reset()         { *m = Income{} }
func (m *Income) String() string { return proto.CompactTextString(m) }
func (*Income) ProtoMessage()    {}
func (*Income) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{2}
}

func (m *Income) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Income.Unmarshal(m, b)
}
func (m *Income) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Income.Marshal(b, m, deterministic)
}
func (m *Income) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Income.Merge(m, src)
}
func (m *Income) XXX_Size() int {
	return xxx_messageInfo_Income.Size(m)
}
func (m *Income) XXX_DiscardUnknown() {
	xxx_messageInfo_Income.DiscardUnknown(m)
}

var xxx_messageInfo_Income proto.InternalMessageInfo

func (m *Income) GetIncome() int32 {
	if m != nil {
		return m.Income
	}
	return 0
}

func (m *Income) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Income) GetUsage() *Usage {
	if m != nil {
		return m.Usage
	}
	return nil
}

type Usage struct {
	CpuTotal             int32    `protobuf:"varint,1,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUsed              int32    `protobuf:"varint,2,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used,omitempty"`
	MemoryTotal          int32    `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed           int32    `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	StorageTotal         int32    `protobuf:"varint,5,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	StorageUsed          int32    `protobuf:"varint,6,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Usage) Reset()         { *m = Usage{} }
func (m *Usage) String() string { return proto.CompactTextString(m) }
func (*Usage) ProtoMessage()    {}
func (*Usage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{3}
}

func (m *Usage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Usage.Unmarshal(m, b)
}
func (m *Usage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Usage.Marshal(b, m, deterministic)
}
func (m *Usage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Usage.Merge(m, src)
}
func (m *Usage) XXX_Size() int {
	return xxx_messageInfo_Usage.Size(m)
}
func (m *Usage) XXX_DiscardUnknown() {
	xxx_messageInfo_Usage.DiscardUnknown(m)
}

var xxx_messageInfo_Usage proto.InternalMessageInfo

func (m *Usage) GetCpuTotal() int32 {
	if m != nil {
		return m.CpuTotal
	}
	return 0
}

func (m *Usage) GetCpuUsed() int32 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *Usage) GetMemoryTotal() int32 {
	if m != nil {
		return m.MemoryTotal
	}
	return 0
}

func (m *Usage) GetMemoryUsed() int32 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *Usage) GetStorageTotal() int32 {
	if m != nil {
		return m.StorageTotal
	}
	return 0
}

func (m *Usage) GetStorageUsed() int32 {
	if m != nil {
		return m.StorageUsed
	}
	return 0
}

type MyDataCenterRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyDataCenterRequest) Reset()         { *m = MyDataCenterRequest{} }
func (m *MyDataCenterRequest) String() string { return proto.CompactTextString(m) }
func (*MyDataCenterRequest) ProtoMessage()    {}
func (*MyDataCenterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{4}
}

func (m *MyDataCenterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyDataCenterRequest.Unmarshal(m, b)
}
func (m *MyDataCenterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyDataCenterRequest.Marshal(b, m, deterministic)
}
func (m *MyDataCenterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyDataCenterRequest.Merge(m, src)
}
func (m *MyDataCenterRequest) XXX_Size() int {
	return xxx_messageInfo_MyDataCenterRequest.Size(m)
}
func (m *MyDataCenterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MyDataCenterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MyDataCenterRequest proto.InternalMessageInfo

func (m *MyDataCenterRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RegisterDataCenterRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDataCenterRequest) Reset()         { *m = RegisterDataCenterRequest{} }
func (m *RegisterDataCenterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterDataCenterRequest) ProtoMessage()    {}
func (*RegisterDataCenterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{5}
}

func (m *RegisterDataCenterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDataCenterRequest.Unmarshal(m, b)
}
func (m *RegisterDataCenterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDataCenterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterDataCenterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDataCenterRequest.Merge(m, src)
}
func (m *RegisterDataCenterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterDataCenterRequest.Size(m)
}
func (m *RegisterDataCenterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDataCenterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDataCenterRequest proto.InternalMessageInfo

func (m *RegisterDataCenterRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterDataCenterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type RegisterDataCenterResponse struct {
	ClientKey            string   `protobuf:"bytes,1,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	ClientCsrCert        string   `protobuf:"bytes,2,opt,name=client_csr_cert,json=clientCsrCert,proto3" json:"client_csr_cert,omitempty"`
	CaCert               string   `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDataCenterResponse) Reset()         { *m = RegisterDataCenterResponse{} }
func (m *RegisterDataCenterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterDataCenterResponse) ProtoMessage()    {}
func (*RegisterDataCenterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{6}
}

func (m *RegisterDataCenterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDataCenterResponse.Unmarshal(m, b)
}
func (m *RegisterDataCenterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDataCenterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterDataCenterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDataCenterResponse.Merge(m, src)
}
func (m *RegisterDataCenterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterDataCenterResponse.Size(m)
}
func (m *RegisterDataCenterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDataCenterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDataCenterResponse proto.InternalMessageInfo

func (m *RegisterDataCenterResponse) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetClientCsrCert() string {
	if m != nil {
		return m.ClientCsrCert
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

type DataCenterListResponse struct {
	DcList               []*common.DataCenterStatus `protobuf:"bytes,1,rep,name=dcList,proto3" json:"dcList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DataCenterListResponse) Reset()         { *m = DataCenterListResponse{} }
func (m *DataCenterListResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListResponse) ProtoMessage()    {}
func (*DataCenterListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{7}
}

func (m *DataCenterListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListResponse.Unmarshal(m, b)
}
func (m *DataCenterListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListResponse.Merge(m, src)
}
func (m *DataCenterListResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListResponse.Size(m)
}
func (m *DataCenterListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListResponse proto.InternalMessageInfo

func (m *DataCenterListResponse) GetDcList() []*common.DataCenterStatus {
	if m != nil {
		return m.DcList
	}
	return nil
}

type NetworkInfoResponse struct {
	UserCount            int32    `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	HostCount            int32    `protobuf:"varint,2,opt,name=host_count,json=hostCount,proto3" json:"host_count,omitempty"`
	NsCount              int32    `protobuf:"varint,3,opt,name=ns_count,json=nsCount,proto3" json:"ns_count,omitempty"`
	ContainerCount       int32    `protobuf:"varint,4,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	Traffic              int32    `protobuf:"varint,5,opt,name=traffic,proto3" json:"traffic,omitempty"`
	CpuTotal             int32    `protobuf:"varint,6,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUsed              int32    `protobuf:"varint,7,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used,omitempty"`
	MemoryTotal          int32    `protobuf:"varint,8,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed           int32    `protobuf:"varint,9,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	StorageTotal         int32    `protobuf:"varint,10,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	StorageUsed          int32    `protobuf:"varint,11,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	NetworkCount         int32    `protobuf:"varint,12,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInfoResponse) Reset()         { *m = NetworkInfoResponse{} }
func (m *NetworkInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkInfoResponse) ProtoMessage()    {}
func (*NetworkInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{8}
}

func (m *NetworkInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfoResponse.Unmarshal(m, b)
}
func (m *NetworkInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfoResponse.Marshal(b, m, deterministic)
}
func (m *NetworkInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfoResponse.Merge(m, src)
}
func (m *NetworkInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkInfoResponse.Size(m)
}
func (m *NetworkInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfoResponse proto.InternalMessageInfo

func (m *NetworkInfoResponse) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetHostCount() int32 {
	if m != nil {
		return m.HostCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetNsCount() int32 {
	if m != nil {
		return m.NsCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetContainerCount() int32 {
	if m != nil {
		return m.ContainerCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetTraffic() int32 {
	if m != nil {
		return m.Traffic
	}
	return 0
}

func (m *NetworkInfoResponse) GetCpuTotal() int32 {
	if m != nil {
		return m.CpuTotal
	}
	return 0
}

func (m *NetworkInfoResponse) GetCpuUsed() int32 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *NetworkInfoResponse) GetMemoryTotal() int32 {
	if m != nil {
		return m.MemoryTotal
	}
	return 0
}

func (m *NetworkInfoResponse) GetMemoryUsed() int32 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *NetworkInfoResponse) GetStorageTotal() int32 {
	if m != nil {
		return m.StorageTotal
	}
	return 0
}

func (m *NetworkInfoResponse) GetStorageUsed() int32 {
	if m != nil {
		return m.StorageUsed
	}
	return 0
}

func (m *NetworkInfoResponse) GetNetworkCount() int32 {
	if m != nil {
		return m.NetworkCount
	}
	return 0
}

type DCOverviewRequest struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCOverviewRequest) Reset()         { *m = DCOverviewRequest{} }
func (m *DCOverviewRequest) String() string { return proto.CompactTextString(m) }
func (*DCOverviewRequest) ProtoMessage()    {}
func (*DCOverviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{9}
}

func (m *DCOverviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCOverviewRequest.Unmarshal(m, b)
}
func (m *DCOverviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCOverviewRequest.Marshal(b, m, deterministic)
}
func (m *DCOverviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCOverviewRequest.Merge(m, src)
}
func (m *DCOverviewRequest) XXX_Size() int {
	return xxx_messageInfo_DCOverviewRequest.Size(m)
}
func (m *DCOverviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCOverviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCOverviewRequest proto.InternalMessageInfo

func (m *DCOverviewRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type DCOverviewResponse struct {
	ClusterId            string                   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Status               *common.DataCenterStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            string                   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            string                   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DCOverviewResponse) Reset()         { *m = DCOverviewResponse{} }
func (m *DCOverviewResponse) String() string { return proto.CompactTextString(m) }
func (*DCOverviewResponse) ProtoMessage()    {}
func (*DCOverviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{10}
}

func (m *DCOverviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCOverviewResponse.Unmarshal(m, b)
}
func (m *DCOverviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCOverviewResponse.Marshal(b, m, deterministic)
}
func (m *DCOverviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCOverviewResponse.Merge(m, src)
}
func (m *DCOverviewResponse) XXX_Size() int {
	return xxx_messageInfo_DCOverviewResponse.Size(m)
}
func (m *DCOverviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DCOverviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DCOverviewResponse proto.InternalMessageInfo

func (m *DCOverviewResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *DCOverviewResponse) GetStatus() *common.DataCenterStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DCOverviewResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DCOverviewResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*DashBoardRequest)(nil), "dcmgr.DashBoardRequest")
	proto.RegisterType((*DashBoardResponse)(nil), "dcmgr.DashBoardResponse")
	proto.RegisterType((*Income)(nil), "dcmgr.Income")
	proto.RegisterType((*Usage)(nil), "dcmgr.Usage")
	proto.RegisterType((*MyDataCenterRequest)(nil), "dcmgr.MyDataCenterRequest")
	proto.RegisterType((*RegisterDataCenterRequest)(nil), "dcmgr.RegisterDataCenterRequest")
	proto.RegisterType((*RegisterDataCenterResponse)(nil), "dcmgr.RegisterDataCenterResponse")
	proto.RegisterType((*DataCenterListResponse)(nil), "dcmgr.DataCenterListResponse")
	proto.RegisterType((*NetworkInfoResponse)(nil), "dcmgr.NetworkInfoResponse")
	proto.RegisterType((*DCOverviewRequest)(nil), "dcmgr.DCOverviewRequest")
	proto.RegisterType((*DCOverviewResponse)(nil), "dcmgr.DCOverviewResponse")
}

func init() { proto.RegisterFile("dcmgr/v1/micro/dcmgr.proto", fileDescriptor_1750e4d9ba65142d) }

var fileDescriptor_1750e4d9ba65142d = []byte{
	// 961 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x95, 0x22, 0x4b, 0x36, 0x47, 0x72, 0xec, 0xac, 0x81, 0x58, 0x66, 0x9a, 0xc6, 0x66, 0x8a,
	0xc6, 0x27, 0x09, 0x56, 0x81, 0x5e, 0x7a, 0x89, 0x2b, 0xa5, 0x85, 0xd0, 0x34, 0x0d, 0x58, 0x1b,
	0x2d, 0xd0, 0x83, 0xc0, 0xac, 0xc6, 0x32, 0x61, 0x91, 0xcb, 0xee, 0x2e, 0x6d, 0x08, 0xe8, 0x77,
	0xf4, 0xd0, 0x1f, 0xe8, 0x0f, 0xf4, 0x2f, 0x7a, 0xed, 0x07, 0x15, 0xbb, 0xb3, 0xa4, 0xa5, 0x48,
	0xb1, 0x02, 0xc4, 0x27, 0x6b, 0xde, 0x9b, 0x79, 0xbb, 0x33, 0x7a, 0x9e, 0x15, 0xf8, 0x63, 0x9e,
	0x4c, 0x64, 0xf7, 0xfa, 0xa4, 0x9b, 0xc4, 0x5c, 0x8a, 0xae, 0x0d, 0x3b, 0x99, 0x14, 0x5a, 0xb0,
	0xba, 0x0d, 0xfc, 0x3d, 0x2e, 0x92, 0x44, 0xa4, 0x5d, 0xfa, 0x43, 0x9c, 0xff, 0x6c, 0x22, 0xc4,
	0x64, 0x8a, 0x5d, 0x1b, 0xbd, 0xcb, 0x2f, 0xba, 0x3a, 0x4e, 0x50, 0xe9, 0x28, 0xc9, 0x28, 0x21,
	0xf8, 0x02, 0x76, 0x07, 0x91, 0xba, 0xfc, 0x56, 0x44, 0x72, 0x1c, 0xe2, 0xef, 0x39, 0x2a, 0xcd,
	0x76, 0xa1, 0x96, 0xc7, 0xe3, 0x76, 0xf5, 0xb0, 0x7a, 0xec, 0x85, 0xe6, 0x63, 0xf0, 0x5f, 0x15,
	0x1e, 0xcd, 0xa5, 0xa9, 0x4c, 0xa4, 0x0a, 0xd9, 0x11, 0xb4, 0xb4, 0xd0, 0xd1, 0x74, 0x14, 0xa7,
	0x5c, 0x24, 0x68, 0x0b, 0xea, 0x61, 0xd3, 0x62, 0x43, 0x0b, 0xb1, 0x13, 0xd8, 0xe6, 0xb9, 0x94,
	0x98, 0xea, 0x51, 0xae, 0xa2, 0x09, 0xb6, 0x1f, 0x1c, 0x56, 0x8f, 0x9b, 0xbd, 0x56, 0x87, 0x1a,
	0x38, 0x37, 0x58, 0xd8, 0x72, 0x29, 0x36, 0x62, 0x47, 0xb0, 0x71, 0x83, 0x78, 0xd5, 0xae, 0x1d,
	0xd6, 0x8e, 0x9b, 0xbd, 0x6d, 0x97, 0x49, 0x7a, 0xa1, 0xa5, 0xd8, 0x73, 0xa8, 0x27, 0x22, 0xd5,
	0x97, 0xed, 0x8d, 0x55, 0x39, 0xc4, 0x19, 0x9d, 0x19, 0x46, 0xb2, 0x5d, 0x5f, 0xa9, 0x63, 0xa8,
	0x40, 0x43, 0xc3, 0xdd, 0xf3, 0x31, 0x34, 0x16, 0x9a, 0x70, 0x11, 0xeb, 0xc0, 0xc6, 0x38, 0xd2,
	0xc5, 0xb5, 0xfd, 0x0e, 0x8d, 0xb3, 0x53, 0x8c, 0xb3, 0x73, 0x56, 0x8c, 0x33, 0xb4, 0x79, 0x2c,
	0x80, 0x3a, 0xf5, 0x59, 0x5b, 0xd1, 0x27, 0x51, 0xc1, 0xbf, 0x55, 0xa8, 0x53, 0xab, 0x4f, 0xc0,
	0xe3, 0x59, 0x3e, 0xb2, 0x03, 0x73, 0x07, 0x6f, 0xf1, 0x2c, 0x3f, 0x33, 0x31, 0x3b, 0x00, 0xf3,
	0x79, 0x94, 0x2b, 0x1c, 0xdb, 0xe3, 0xeb, 0xe1, 0x26, 0xcf, 0xf2, 0x73, 0x85, 0x63, 0x33, 0xf8,
	0x04, 0x13, 0x21, 0x67, 0xae, 0xb4, 0x46, 0x83, 0x27, 0x8c, 0xaa, 0x9f, 0x81, 0x0b, 0x49, 0x60,
	0xc3, 0x66, 0x00, 0x41, 0x56, 0xe3, 0x39, 0x6c, 0x2b, 0x2d, 0x64, 0x34, 0x41, 0x27, 0x52, 0xb7,
	0x29, 0x2d, 0x07, 0x92, 0xca, 0x11, 0x14, 0x31, 0xc9, 0x34, 0xe8, 0x20, 0x87, 0x19, 0x9d, 0xe0,
	0x05, 0xec, 0xfd, 0x38, 0x1b, 0x44, 0x3a, 0xea, 0x63, 0xaa, 0x51, 0x7e, 0xd8, 0x43, 0xbf, 0xc0,
	0x41, 0x88, 0x93, 0x58, 0x69, 0x94, 0xcb, 0xe9, 0xfb, 0xb0, 0x99, 0x2b, 0x94, 0xa3, 0xb2, 0xa4,
	0x61, 0xc2, 0xa1, 0x6d, 0x95, 0x4f, 0x73, 0x53, 0x34, 0x4a, 0xa3, 0x84, 0xbe, 0x08, 0x2f, 0x6c,
	0x3a, 0xec, 0x4d, 0x94, 0x60, 0xf0, 0x07, 0xf8, 0xab, 0x84, 0x9d, 0x49, 0x9f, 0x02, 0xf0, 0x69,
	0x6c, 0x0c, 0x78, 0x85, 0x33, 0x27, 0xee, 0x11, 0xf2, 0x03, 0xce, 0xd8, 0x97, 0xb0, 0xe3, 0x68,
	0xae, 0xe4, 0x88, 0xa3, 0xd4, 0xee, 0x88, 0x6d, 0x82, 0xfb, 0x4a, 0xf6, 0x51, 0xda, 0x0b, 0xf2,
	0x88, 0xf8, 0x1a, 0x5d, 0x90, 0x47, 0x86, 0x08, 0xde, 0xc2, 0xe3, 0xdb, 0x53, 0x5f, 0xc7, 0x4a,
	0x97, 0x27, 0x7f, 0x0d, 0x8d, 0x31, 0x37, 0x48, 0xbb, 0x6a, 0x2d, 0xf8, 0x79, 0x67, 0xfe, 0x5f,
	0xb3, 0x73, 0x5b, 0xf5, 0xb3, 0x8e, 0x74, 0xae, 0x42, 0x97, 0x1d, 0xfc, 0x55, 0x83, 0xbd, 0x37,
	0xa8, 0x6f, 0x84, 0xbc, 0x1a, 0xa6, 0x17, 0x62, 0xbe, 0x13, 0x3b, 0x23, 0x2e, 0xf2, 0x54, 0x3b,
	0xbb, 0x78, 0x06, 0xe9, 0x1b, 0xc0, 0xd0, 0x97, 0x42, 0x69, 0x47, 0x93, 0x63, 0x3c, 0x83, 0x10,
	0x7d, 0x00, 0x5b, 0xa9, 0x72, 0x24, 0xf9, 0x65, 0x33, 0x55, 0x44, 0xbd, 0x80, 0x1d, 0x2e, 0x52,
	0x1d, 0xc5, 0x69, 0xa9, 0x4e, 0x7e, 0x79, 0x58, 0xc2, 0x94, 0xd8, 0x86, 0x4d, 0x2d, 0xa3, 0x8b,
	0x8b, 0x98, 0x3b, 0xb7, 0x14, 0xe1, 0xa2, 0x93, 0x1b, 0x77, 0x38, 0x79, 0xf3, 0x6e, 0x27, 0x6f,
	0xad, 0x75, 0xb2, 0xb7, 0xde, 0xc9, 0xf0, 0x11, 0x4e, 0x6e, 0x2e, 0x39, 0xd9, 0xe8, 0xa4, 0x34,
	0x76, 0x37, 0x84, 0x16, 0xe9, 0x38, 0xd0, 0x8e, 0x20, 0x38, 0x81, 0x47, 0x83, 0xfe, 0x4f, 0xd7,
	0x28, 0xaf, 0x63, 0xbc, 0x29, 0xdc, 0xfb, 0x19, 0x78, 0xe5, 0x5e, 0x2d, 0x2c, 0x56, 0x02, 0xc1,
	0xdf, 0x55, 0x60, 0xf3, 0x35, 0xf3, 0xc6, 0x24, 0x67, 0x97, 0xae, 0xf7, 0x1c, 0x32, 0x1c, 0x1b,
	0xf7, 0x28, 0xeb, 0x0b, 0xb7, 0x7b, 0xd6, 0xba, 0x87, 0xb2, 0x17, 0xef, 0x52, 0x7b, 0xef, 0x2e,
	0x86, 0x55, 0xf1, 0x24, 0x8d, 0x74, 0x2e, 0xd1, 0x7e, 0xc9, 0x5e, 0x78, 0x0b, 0xf4, 0xfe, 0xd9,
	0x80, 0x07, 0x83, 0x3e, 0x7b, 0x05, 0x5e, 0x5f, 0x62, 0xa4, 0xf1, 0x34, 0xcb, 0xd8, 0x93, 0xc5,
	0x73, 0x4f, 0xb3, 0x6c, 0x80, 0xd9, 0x54, 0xcc, 0x12, 0x4c, 0xb5, 0x7f, 0xb0, 0x44, 0x52, 0x7b,
	0x1c, 0x83, 0x8a, 0x91, 0x39, 0xcf, 0xc6, 0xf7, 0x21, 0x33, 0xc0, 0x29, 0x7e, 0xaa, 0xcc, 0xf7,
	0xb0, 0x43, 0x4d, 0x99, 0x9d, 0xa1, 0xb2, 0x88, 0x23, 0xdb, 0x5f, 0xcc, 0x2f, 0x89, 0xb5, 0x42,
	0xd4, 0xd6, 0x3d, 0x08, 0x51, 0x63, 0x9f, 0x2a, 0xf4, 0x0d, 0x34, 0xc8, 0x04, 0x6c, 0x6f, 0x29,
	0x6d, 0x38, 0xf0, 0xfd, 0xe5, 0xda, 0x3c, 0xa5, 0x82, 0xa0, 0xc2, 0x4e, 0x61, 0xab, 0xb0, 0x26,
	0x6b, 0xbb, 0xe7, 0x6a, 0xc9, 0xe1, 0xfe, 0xc1, 0x0a, 0x86, 0x7c, 0x1c, 0x54, 0x7a, 0x7f, 0xd6,
	0xa0, 0x3e, 0xe8, 0x9f, 0xbe, 0x1d, 0xb2, 0xef, 0xe0, 0xe1, 0xe2, 0x32, 0x7c, 0xff, 0x46, 0xaf,
	0x92, 0x4c, 0xcf, 0xfc, 0xa7, 0x85, 0xda, 0xca, 0xc5, 0x19, 0x54, 0xd8, 0x4b, 0x68, 0xce, 0x6d,
	0xc0, 0xd5, 0x22, 0xbe, 0x13, 0x59, 0xb1, 0x2a, 0x83, 0x0a, 0xfb, 0x0d, 0xd8, 0xf2, 0xa3, 0xc0,
	0x0e, 0x5d, 0xcd, 0x07, 0x1f, 0x22, 0xff, 0xe8, 0x8e, 0x8c, 0x52, 0xfc, 0x57, 0xd8, 0x09, 0x51,
	0xa1, 0xbe, 0x7f, 0xe5, 0xd7, 0xd0, 0x9a, 0x7f, 0x4d, 0x59, 0xd1, 0xe4, 0x8a, 0x27, 0xd6, 0x5f,
	0xb3, 0x11, 0x82, 0x4a, 0xef, 0x0c, 0x76, 0xfb, 0xb4, 0x50, 0xca, 0x1f, 0x6f, 0xec, 0x25, 0x78,
	0xb7, 0xc1, 0x7e, 0xf9, 0x45, 0x2c, 0xfe, 0x04, 0xf4, 0xdb, 0xcb, 0x44, 0x71, 0xc7, 0x77, 0x0d,
	0x7b, 0xde, 0x57, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x3b, 0xe7, 0xc5, 0x94, 0x0a, 0x00,
	0x00,
}
