// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rolemgr/v1/micro/role.proto

package rolemgr

import (
	fmt "fmt"
	_ "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrivilegeElement struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeElement) Reset()         { *m = PrivilegeElement{} }
func (m *PrivilegeElement) String() string { return proto.CompactTextString(m) }
func (*PrivilegeElement) ProtoMessage()    {}
func (*PrivilegeElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{0}
}

func (m *PrivilegeElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeElement.Unmarshal(m, b)
}
func (m *PrivilegeElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeElement.Marshal(b, m, deterministic)
}
func (m *PrivilegeElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeElement.Merge(m, src)
}
func (m *PrivilegeElement) XXX_Size() int {
	return xxx_messageInfo_PrivilegeElement.Size(m)
}
func (m *PrivilegeElement) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeElement.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeElement proto.InternalMessageInfo

func (m *PrivilegeElement) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PrivilegeElement) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Privilege struct {
	List                 []*PrivilegeElement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Privilege) Reset()         { *m = Privilege{} }
func (m *Privilege) String() string { return proto.CompactTextString(m) }
func (*Privilege) ProtoMessage()    {}
func (*Privilege) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{1}
}

func (m *Privilege) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Privilege.Unmarshal(m, b)
}
func (m *Privilege) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Privilege.Marshal(b, m, deterministic)
}
func (m *Privilege) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Privilege.Merge(m, src)
}
func (m *Privilege) XXX_Size() int {
	return xxx_messageInfo_Privilege.Size(m)
}
func (m *Privilege) XXX_DiscardUnknown() {
	xxx_messageInfo_Privilege.DiscardUnknown(m)
}

var xxx_messageInfo_Privilege proto.InternalMessageInfo

func (m *Privilege) GetList() []*PrivilegeElement {
	if m != nil {
		return m.List
	}
	return nil
}

type CreateTeamRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTeamRequest) Reset()         { *m = CreateTeamRequest{} }
func (m *CreateTeamRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTeamRequest) ProtoMessage()    {}
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{2}
}

func (m *CreateTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamRequest.Unmarshal(m, b)
}
func (m *CreateTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamRequest.Marshal(b, m, deterministic)
}
func (m *CreateTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamRequest.Merge(m, src)
}
func (m *CreateTeamRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTeamRequest.Size(m)
}
func (m *CreateTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamRequest proto.InternalMessageInfo

func (m *CreateTeamRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CreateTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateTeamResponse struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTeamResponse) Reset()         { *m = CreateTeamResponse{} }
func (m *CreateTeamResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTeamResponse) ProtoMessage()    {}
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{3}
}

func (m *CreateTeamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamResponse.Unmarshal(m, b)
}
func (m *CreateTeamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamResponse.Marshal(b, m, deterministic)
}
func (m *CreateTeamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamResponse.Merge(m, src)
}
func (m *CreateTeamResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTeamResponse.Size(m)
}
func (m *CreateTeamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamResponse proto.InternalMessageInfo

func (m *CreateTeamResponse) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type GetUserRoleRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRoleRequest) Reset()         { *m = GetUserRoleRequest{} }
func (m *GetUserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRoleRequest) ProtoMessage()    {}
func (*GetUserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{4}
}

func (m *GetUserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRoleRequest.Unmarshal(m, b)
}
func (m *GetUserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRoleRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRoleRequest.Merge(m, src)
}
func (m *GetUserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRoleRequest.Size(m)
}
func (m *GetUserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRoleRequest proto.InternalMessageInfo

func (m *GetUserRoleRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetUserRoleResponse struct {
	TeamId               string     `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Role                 string     `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Privilege            *Privilege `protobuf:"bytes,3,opt,name=privilege,proto3" json:"privilege,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUserRoleResponse) Reset()         { *m = GetUserRoleResponse{} }
func (m *GetUserRoleResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserRoleResponse) ProtoMessage()    {}
func (*GetUserRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{5}
}

func (m *GetUserRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRoleResponse.Unmarshal(m, b)
}
func (m *GetUserRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRoleResponse.Marshal(b, m, deterministic)
}
func (m *GetUserRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRoleResponse.Merge(m, src)
}
func (m *GetUserRoleResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserRoleResponse.Size(m)
}
func (m *GetUserRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRoleResponse proto.InternalMessageInfo

func (m *GetUserRoleResponse) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *GetUserRoleResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetUserRoleResponse) GetPrivilege() *Privilege {
	if m != nil {
		return m.Privilege
	}
	return nil
}

type InviteUserRequest struct {
	Mame                 string   `protobuf:"bytes,1,opt,name=mame,proto3" json:"mame,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	TeamId               string   `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserRequest) Reset()         { *m = InviteUserRequest{} }
func (m *InviteUserRequest) String() string { return proto.CompactTextString(m) }
func (*InviteUserRequest) ProtoMessage()    {}
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{6}
}

func (m *InviteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserRequest.Unmarshal(m, b)
}
func (m *InviteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserRequest.Marshal(b, m, deterministic)
}
func (m *InviteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserRequest.Merge(m, src)
}
func (m *InviteUserRequest) XXX_Size() int {
	return xxx_messageInfo_InviteUserRequest.Size(m)
}
func (m *InviteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserRequest proto.InternalMessageInfo

func (m *InviteUserRequest) GetMame() string {
	if m != nil {
		return m.Mame
	}
	return ""
}

func (m *InviteUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteUserRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type TeamUsersRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamUsersRequest) Reset()         { *m = TeamUsersRequest{} }
func (m *TeamUsersRequest) String() string { return proto.CompactTextString(m) }
func (*TeamUsersRequest) ProtoMessage()    {}
func (*TeamUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{7}
}

func (m *TeamUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamUsersRequest.Unmarshal(m, b)
}
func (m *TeamUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamUsersRequest.Marshal(b, m, deterministic)
}
func (m *TeamUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamUsersRequest.Merge(m, src)
}
func (m *TeamUsersRequest) XXX_Size() int {
	return xxx_messageInfo_TeamUsersRequest.Size(m)
}
func (m *TeamUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamUsersRequest proto.InternalMessageInfo

func (m *TeamUsersRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type TeamUserRecord struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string     `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Privilege            *Privilege `protobuf:"bytes,5,opt,name=privilege,proto3" json:"privilege,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TeamUserRecord) Reset()         { *m = TeamUserRecord{} }
func (m *TeamUserRecord) String() string { return proto.CompactTextString(m) }
func (*TeamUserRecord) ProtoMessage()    {}
func (*TeamUserRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{8}
}

func (m *TeamUserRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamUserRecord.Unmarshal(m, b)
}
func (m *TeamUserRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamUserRecord.Marshal(b, m, deterministic)
}
func (m *TeamUserRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamUserRecord.Merge(m, src)
}
func (m *TeamUserRecord) XXX_Size() int {
	return xxx_messageInfo_TeamUserRecord.Size(m)
}
func (m *TeamUserRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamUserRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TeamUserRecord proto.InternalMessageInfo

func (m *TeamUserRecord) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TeamUserRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeamUserRecord) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *TeamUserRecord) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *TeamUserRecord) GetPrivilege() *Privilege {
	if m != nil {
		return m.Privilege
	}
	return nil
}

type TeamUsersResponse struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamId               string            `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Users                []*TeamUserRecord `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TeamUsersResponse) Reset()         { *m = TeamUsersResponse{} }
func (m *TeamUsersResponse) String() string { return proto.CompactTextString(m) }
func (*TeamUsersResponse) ProtoMessage()    {}
func (*TeamUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{9}
}

func (m *TeamUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamUsersResponse.Unmarshal(m, b)
}
func (m *TeamUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamUsersResponse.Marshal(b, m, deterministic)
}
func (m *TeamUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamUsersResponse.Merge(m, src)
}
func (m *TeamUsersResponse) XXX_Size() int {
	return xxx_messageInfo_TeamUsersResponse.Size(m)
}
func (m *TeamUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamUsersResponse proto.InternalMessageInfo

func (m *TeamUsersResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeamUsersResponse) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *TeamUsersResponse) GetUsers() []*TeamUserRecord {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateUserRoleRequest struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role                 string     `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Privilege            *Privilege `protobuf:"bytes,3,opt,name=privilege,proto3" json:"privilege,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateUserRoleRequest) Reset()         { *m = UpdateUserRoleRequest{} }
func (m *UpdateUserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRoleRequest) ProtoMessage()    {}
func (*UpdateUserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81bf85120288ab8, []int{10}
}

func (m *UpdateUserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRoleRequest.Unmarshal(m, b)
}
func (m *UpdateUserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRoleRequest.Merge(m, src)
}
func (m *UpdateUserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRoleRequest.Size(m)
}
func (m *UpdateUserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRoleRequest proto.InternalMessageInfo

func (m *UpdateUserRoleRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UpdateUserRoleRequest) GetPrivilege() *Privilege {
	if m != nil {
		return m.Privilege
	}
	return nil
}

func init() {
	proto.RegisterType((*PrivilegeElement)(nil), "rolemgr.PrivilegeElement")
	proto.RegisterType((*Privilege)(nil), "rolemgr.Privilege")
	proto.RegisterType((*CreateTeamRequest)(nil), "rolemgr.CreateTeamRequest")
	proto.RegisterType((*CreateTeamResponse)(nil), "rolemgr.CreateTeamResponse")
	proto.RegisterType((*GetUserRoleRequest)(nil), "rolemgr.GetUserRoleRequest")
	proto.RegisterType((*GetUserRoleResponse)(nil), "rolemgr.GetUserRoleResponse")
	proto.RegisterType((*InviteUserRequest)(nil), "rolemgr.InviteUserRequest")
	proto.RegisterType((*TeamUsersRequest)(nil), "rolemgr.TeamUsersRequest")
	proto.RegisterType((*TeamUserRecord)(nil), "rolemgr.TeamUserRecord")
	proto.RegisterType((*TeamUsersResponse)(nil), "rolemgr.TeamUsersResponse")
	proto.RegisterType((*UpdateUserRoleRequest)(nil), "rolemgr.UpdateUserRoleRequest")
}

func init() { proto.RegisterFile("rolemgr/v1/micro/role.proto", fileDescriptor_b81bf85120288ab8) }

var fileDescriptor_b81bf85120288ab8 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x63, 0xa7, 0x55, 0x26, 0x52, 0x95, 0x4c, 0x40, 0x75, 0x5d, 0x84, 0xa2, 0x3d, 0xa0,
	0x48, 0x28, 0x0e, 0x84, 0x13, 0xbd, 0x70, 0x80, 0x2a, 0x2a, 0x27, 0x64, 0xb5, 0x5c, 0x91, 0x49,
	0x46, 0xc5, 0x92, 0xd7, 0x6b, 0xec, 0x4d, 0xa4, 0xbe, 0x06, 0xaf, 0xc9, 0x4b, 0xa0, 0xf5, 0xcf,
	0x7a, 0x8d, 0x13, 0xc8, 0xa1, 0x27, 0xcf, 0xee, 0xfc, 0x7c, 0xdf, 0xcc, 0x37, 0x6b, 0xb8, 0xca,
	0x44, 0x4c, 0xfc, 0x21, 0x5b, 0xec, 0xde, 0x2e, 0x78, 0xb4, 0xce, 0xc4, 0x42, 0x5d, 0xf8, 0x69,
	0x26, 0xa4, 0xc0, 0xb3, 0xca, 0xe9, 0x4d, 0xd6, 0x82, 0x73, 0x91, 0x2c, 0xca, 0x4f, 0xe9, 0x65,
	0xd7, 0x30, 0xfa, 0x92, 0x45, 0xbb, 0x28, 0xa6, 0x07, 0xba, 0x89, 0x89, 0x53, 0x22, 0x11, 0xc1,
	0xb9, 0x7b, 0x4c, 0xc9, 0xb5, 0xa6, 0xd6, 0x6c, 0x10, 0x14, 0xb6, 0xba, 0x4b, 0x43, 0xf9, 0xc3,
	0xed, 0x95, 0x77, 0xca, 0x66, 0xd7, 0x30, 0xd0, 0xb9, 0x38, 0x07, 0x27, 0x8e, 0x72, 0xe9, 0x5a,
	0x53, 0x7b, 0x36, 0x5c, 0x5e, 0xfa, 0x15, 0xaa, 0xff, 0x77, 0xf5, 0xa0, 0x08, 0x63, 0xef, 0x61,
	0xfc, 0x31, 0xa3, 0x50, 0xd2, 0x1d, 0x85, 0x3c, 0xa0, 0x9f, 0x5b, 0xca, 0x25, 0x8e, 0xc0, 0xde,
	0x46, 0x9b, 0x0a, 0x57, 0x99, 0x0a, 0x36, 0x09, 0x39, 0xd5, 0xb0, 0xca, 0x66, 0x73, 0x40, 0x33,
	0x35, 0x4f, 0x45, 0x92, 0x13, 0x5e, 0xc0, 0x99, 0xa4, 0x90, 0x7f, 0xd3, 0xf9, 0xa7, 0xea, 0x78,
	0xbb, 0x61, 0xaf, 0x00, 0x57, 0x24, 0xef, 0x73, 0xca, 0x02, 0x11, 0xd3, 0x41, 0x28, 0x26, 0x61,
	0xd2, 0x8a, 0xfb, 0x4f, 0x5d, 0x45, 0x4d, 0xf5, 0x58, 0x53, 0x53, 0x36, 0xbe, 0x81, 0x41, 0x5a,
	0xf7, 0xeb, 0xda, 0x53, 0x6b, 0x36, 0x5c, 0x62, 0x77, 0x12, 0x41, 0x13, 0xc4, 0xbe, 0xc2, 0xf8,
	0x36, 0xd9, 0x45, 0x92, 0x0a, 0xe0, 0x8a, 0x1c, 0x82, 0xc3, 0x55, 0xd7, 0x95, 0x00, 0xca, 0xc6,
	0x67, 0xd0, 0x27, 0x1e, 0x46, 0x71, 0x85, 0x57, 0x1e, 0x4c, 0x76, 0x76, 0xab, 0xeb, 0xd7, 0x30,
	0x52, 0xe3, 0x51, 0x55, 0xf3, 0xba, 0xec, 0xc1, 0x11, 0xfd, 0xb2, 0xe0, 0xbc, 0x8e, 0x0e, 0x68,
	0x2d, 0xb2, 0xcd, 0x71, 0x52, 0x34, 0xa4, 0x6c, 0x93, 0x54, 0x3d, 0x19, 0xe7, 0xd0, 0x64, 0xfa,
	0xc7, 0x4c, 0x46, 0xc0, 0xd8, 0xe8, 0xa0, 0x52, 0xa3, 0x26, 0x61, 0x19, 0x24, 0x8c, 0xb6, 0x7a,
	0x2d, 0x85, 0xe6, 0xd0, 0xdf, 0xaa, 0x6c, 0xd7, 0x2e, 0x76, 0xf2, 0x42, 0xe3, 0xb5, 0x7b, 0x0d,
	0xca, 0x28, 0x26, 0xe0, 0xf9, 0x7d, 0xba, 0x09, 0x2b, 0x29, 0xfe, 0xb5, 0x2b, 0x4f, 0xa3, 0xfd,
	0xf2, 0x77, 0x0f, 0x1c, 0x85, 0x83, 0x2b, 0x80, 0x66, 0xa3, 0xd1, 0xd3, 0x59, 0x9d, 0x17, 0xe2,
	0x5d, 0xed, 0xf5, 0x95, 0xc3, 0x61, 0x27, 0xf8, 0x19, 0x86, 0xc6, 0x0e, 0x63, 0x13, 0xdd, 0x7d,
	0x01, 0xde, 0x8b, 0xfd, 0x4e, 0x5d, 0xeb, 0x03, 0x40, 0xb3, 0x99, 0x06, 0xa9, 0xce, 0xba, 0x7a,
	0x13, 0xdf, 0xfc, 0xa5, 0xf8, 0x37, 0x3c, 0x95, 0x8f, 0xec, 0x04, 0x3f, 0xc1, 0x40, 0x0b, 0x88,
	0x97, 0x9d, 0xe1, 0xd7, 0x6b, 0xe9, 0x79, 0xfb, 0x5c, 0x9a, 0xc6, 0x0a, 0xce, 0xdb, 0xaa, 0xe0,
	0x4b, 0x1d, 0xbf, 0x57, 0xae, 0x03, 0x74, 0xbe, 0x9f, 0x16, 0xc7, 0x77, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x99, 0xd5, 0x14, 0x16, 0x2d, 0x05, 0x00, 0x00,
}
