// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcmgr/v1/dcmgr.proto

package gwexdcmgr

import (
	context "context"
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataCenterListResponse struct {
	DcList               []*common.DataCenterStatus `protobuf:"bytes,1,rep,name=dcList,proto3" json:"dcList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DataCenterListResponse) Reset()         { *m = DataCenterListResponse{} }
func (m *DataCenterListResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListResponse) ProtoMessage()    {}
func (*DataCenterListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5063cc471a821220, []int{0}
}

func (m *DataCenterListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListResponse.Unmarshal(m, b)
}
func (m *DataCenterListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListResponse.Merge(m, src)
}
func (m *DataCenterListResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListResponse.Size(m)
}
func (m *DataCenterListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListResponse proto.InternalMessageInfo

func (m *DataCenterListResponse) GetDcList() []*common.DataCenterStatus {
	if m != nil {
		return m.DcList
	}
	return nil
}

type NetworkInfoResponse struct {
	UserCount            int32    `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	HostCount            int32    `protobuf:"varint,2,opt,name=host_count,json=hostCount,proto3" json:"host_count,omitempty"`
	NsCount              int32    `protobuf:"varint,3,opt,name=ns_count,json=nsCount,proto3" json:"ns_count,omitempty"`
	ContainerCount       int32    `protobuf:"varint,4,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	Traffic              int32    `protobuf:"varint,5,opt,name=traffic,proto3" json:"traffic,omitempty"`
	CpuTotal             string   `protobuf:"bytes,6,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUsed              string   `protobuf:"bytes,7,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used,omitempty"`
	MemoryTotal          string   `protobuf:"bytes,8,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed           string   `protobuf:"bytes,9,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	StorageTotal         string   `protobuf:"bytes,10,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	StorageUsed          string   `protobuf:"bytes,11,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	NetworkCount         int32    `protobuf:"varint,12,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInfoResponse) Reset()         { *m = NetworkInfoResponse{} }
func (m *NetworkInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkInfoResponse) ProtoMessage()    {}
func (*NetworkInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5063cc471a821220, []int{1}
}

func (m *NetworkInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfoResponse.Unmarshal(m, b)
}
func (m *NetworkInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfoResponse.Marshal(b, m, deterministic)
}
func (m *NetworkInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfoResponse.Merge(m, src)
}
func (m *NetworkInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkInfoResponse.Size(m)
}
func (m *NetworkInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfoResponse proto.InternalMessageInfo

func (m *NetworkInfoResponse) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetHostCount() int32 {
	if m != nil {
		return m.HostCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetNsCount() int32 {
	if m != nil {
		return m.NsCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetContainerCount() int32 {
	if m != nil {
		return m.ContainerCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetTraffic() int32 {
	if m != nil {
		return m.Traffic
	}
	return 0
}

func (m *NetworkInfoResponse) GetCpuTotal() string {
	if m != nil {
		return m.CpuTotal
	}
	return ""
}

func (m *NetworkInfoResponse) GetCpuUsed() string {
	if m != nil {
		return m.CpuUsed
	}
	return ""
}

func (m *NetworkInfoResponse) GetMemoryTotal() string {
	if m != nil {
		return m.MemoryTotal
	}
	return ""
}

func (m *NetworkInfoResponse) GetMemoryUsed() string {
	if m != nil {
		return m.MemoryUsed
	}
	return ""
}

func (m *NetworkInfoResponse) GetStorageTotal() string {
	if m != nil {
		return m.StorageTotal
	}
	return ""
}

func (m *NetworkInfoResponse) GetStorageUsed() string {
	if m != nil {
		return m.StorageUsed
	}
	return ""
}

func (m *NetworkInfoResponse) GetNetworkCount() int32 {
	if m != nil {
		return m.NetworkCount
	}
	return 0
}

type DataCenterLeaderBoardDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number               float64  `protobuf:"fixed64,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataCenterLeaderBoardDetail) Reset()         { *m = DataCenterLeaderBoardDetail{} }
func (m *DataCenterLeaderBoardDetail) String() string { return proto.CompactTextString(m) }
func (*DataCenterLeaderBoardDetail) ProtoMessage()    {}
func (*DataCenterLeaderBoardDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_5063cc471a821220, []int{2}
}

func (m *DataCenterLeaderBoardDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterLeaderBoardDetail.Unmarshal(m, b)
}
func (m *DataCenterLeaderBoardDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterLeaderBoardDetail.Marshal(b, m, deterministic)
}
func (m *DataCenterLeaderBoardDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterLeaderBoardDetail.Merge(m, src)
}
func (m *DataCenterLeaderBoardDetail) XXX_Size() int {
	return xxx_messageInfo_DataCenterLeaderBoardDetail.Size(m)
}
func (m *DataCenterLeaderBoardDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterLeaderBoardDetail.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterLeaderBoardDetail proto.InternalMessageInfo

func (m *DataCenterLeaderBoardDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataCenterLeaderBoardDetail) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type MyDataCenterRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyDataCenterRequest) Reset()         { *m = MyDataCenterRequest{} }
func (m *MyDataCenterRequest) String() string { return proto.CompactTextString(m) }
func (*MyDataCenterRequest) ProtoMessage()    {}
func (*MyDataCenterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5063cc471a821220, []int{3}
}

func (m *MyDataCenterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyDataCenterRequest.Unmarshal(m, b)
}
func (m *MyDataCenterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyDataCenterRequest.Marshal(b, m, deterministic)
}
func (m *MyDataCenterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyDataCenterRequest.Merge(m, src)
}
func (m *MyDataCenterRequest) XXX_Size() int {
	return xxx_messageInfo_MyDataCenterRequest.Size(m)
}
func (m *MyDataCenterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MyDataCenterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MyDataCenterRequest proto.InternalMessageInfo

func (m *MyDataCenterRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RegisterDataCenterRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDataCenterRequest) Reset()         { *m = RegisterDataCenterRequest{} }
func (m *RegisterDataCenterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterDataCenterRequest) ProtoMessage()    {}
func (*RegisterDataCenterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5063cc471a821220, []int{4}
}

func (m *RegisterDataCenterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDataCenterRequest.Unmarshal(m, b)
}
func (m *RegisterDataCenterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDataCenterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterDataCenterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDataCenterRequest.Merge(m, src)
}
func (m *RegisterDataCenterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterDataCenterRequest.Size(m)
}
func (m *RegisterDataCenterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDataCenterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDataCenterRequest proto.InternalMessageInfo

func (m *RegisterDataCenterRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterDataCenterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type RegisterDataCenterResponse struct {
	ClientKey            string   `protobuf:"bytes,1,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	ClientCsrCert        string   `protobuf:"bytes,2,opt,name=client_csr_cert,json=clientCsrCert,proto3" json:"client_csr_cert,omitempty"`
	CaCert               string   `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDataCenterResponse) Reset()         { *m = RegisterDataCenterResponse{} }
func (m *RegisterDataCenterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterDataCenterResponse) ProtoMessage()    {}
func (*RegisterDataCenterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5063cc471a821220, []int{5}
}

func (m *RegisterDataCenterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDataCenterResponse.Unmarshal(m, b)
}
func (m *RegisterDataCenterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDataCenterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterDataCenterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDataCenterResponse.Merge(m, src)
}
func (m *RegisterDataCenterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterDataCenterResponse.Size(m)
}
func (m *RegisterDataCenterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDataCenterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDataCenterResponse proto.InternalMessageInfo

func (m *RegisterDataCenterResponse) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetClientCsrCert() string {
	if m != nil {
		return m.ClientCsrCert
	}
	return ""
}

func (m *RegisterDataCenterResponse) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func init() {
	proto.RegisterType((*DataCenterListResponse)(nil), "gwexdcmgr.DataCenterListResponse")
	proto.RegisterType((*NetworkInfoResponse)(nil), "gwexdcmgr.NetworkInfoResponse")
	proto.RegisterType((*DataCenterLeaderBoardDetail)(nil), "gwexdcmgr.DataCenterLeaderBoardDetail")
	proto.RegisterType((*MyDataCenterRequest)(nil), "gwexdcmgr.MyDataCenterRequest")
	proto.RegisterType((*RegisterDataCenterRequest)(nil), "gwexdcmgr.RegisterDataCenterRequest")
	proto.RegisterType((*RegisterDataCenterResponse)(nil), "gwexdcmgr.RegisterDataCenterResponse")
}

func init() { proto.RegisterFile("dcmgr/v1/dcmgr.proto", fileDescriptor_5063cc471a821220) }

var fileDescriptor_5063cc471a821220 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x72, 0x12, 0x4f,
	0x10, 0xc7, 0x7f, 0x84, 0x04, 0xd8, 0x86, 0x84, 0x9f, 0x43, 0x2a, 0x21, 0x44, 0x63, 0xb2, 0xfe,
	0xa3, 0x3c, 0x80, 0xc6, 0x2a, 0x0f, 0xde, 0x14, 0x3c, 0x50, 0x6a, 0x2a, 0xb5, 0xd1, 0xb2, 0x4a,
	0x0f, 0x38, 0x99, 0xed, 0xe0, 0x56, 0xd8, 0x19, 0x9c, 0x99, 0x4d, 0xc4, 0xf2, 0xe4, 0x2b, 0xe8,
	0xc9, 0xd7, 0xf2, 0x15, 0x7c, 0x10, 0x6b, 0xfe, 0x84, 0x80, 0x92, 0x8a, 0x17, 0x4f, 0xd0, 0xdf,
	0x6f, 0xf7, 0xa7, 0x77, 0xa7, 0xa7, 0x17, 0x56, 0x63, 0x96, 0x0e, 0x64, 0xfb, 0xe4, 0x7e, 0xdb,
	0xfe, 0x69, 0x8d, 0xa4, 0xd0, 0x82, 0x04, 0x83, 0x53, 0xfc, 0x68, 0x85, 0xc6, 0xd5, 0x81, 0x10,
	0x83, 0x21, 0xb6, 0xe9, 0x28, 0x69, 0x53, 0xce, 0x85, 0xa6, 0x3a, 0x11, 0x5c, 0xb9, 0xc4, 0x46,
	0x8d, 0x89, 0x34, 0x15, 0xbc, 0xed, 0x7e, 0x9c, 0x18, 0xee, 0xc3, 0x5a, 0x97, 0x6a, 0xda, 0x41,
	0xae, 0x51, 0x3e, 0x4f, 0x94, 0x8e, 0x50, 0x8d, 0x04, 0x57, 0x48, 0x1e, 0x42, 0x21, 0x66, 0x46,
	0xa9, 0xe7, 0xb6, 0xf3, 0xcd, 0xf2, 0xee, 0x56, 0x6b, 0xba, 0xb0, 0x75, 0x5e, 0x75, 0xa0, 0xa9,
	0xce, 0x54, 0xe4, 0xb3, 0xc3, 0xef, 0x79, 0xa8, 0xed, 0xa1, 0x3e, 0x15, 0xf2, 0xb8, 0xc7, 0x8f,
	0xc4, 0x84, 0x77, 0x0d, 0x20, 0x53, 0x28, 0xfb, 0x4c, 0x64, 0xdc, 0x30, 0x73, 0xcd, 0xa5, 0x28,
	0x30, 0x4a, 0xc7, 0x08, 0xc6, 0x7e, 0x2f, 0x94, 0xf6, 0xf6, 0x82, 0xb3, 0x8d, 0xe2, 0xec, 0x0d,
	0x28, 0x71, 0xe5, 0xcd, 0xbc, 0x35, 0x8b, 0x5c, 0x39, 0xeb, 0x0e, 0x54, 0x99, 0xe0, 0x9a, 0x26,
	0x7c, 0x42, 0x5f, 0xb4, 0x19, 0x2b, 0x13, 0xd9, 0x25, 0xd6, 0xa1, 0xa8, 0x25, 0x3d, 0x3a, 0x4a,
	0x58, 0x7d, 0xc9, 0x21, 0x7c, 0x48, 0x36, 0x21, 0x60, 0xa3, 0xac, 0xaf, 0x85, 0xa6, 0xc3, 0x7a,
	0x61, 0x3b, 0xd7, 0x0c, 0xa2, 0x12, 0x1b, 0x65, 0x2f, 0x4d, 0x6c, 0x5a, 0x1b, 0x33, 0x53, 0x18,
	0xd7, 0x8b, 0xd6, 0x2b, 0xb2, 0x51, 0xf6, 0x4a, 0x61, 0x4c, 0x76, 0xa0, 0x92, 0x62, 0x2a, 0xe4,
	0xd8, 0x97, 0x96, 0xac, 0x5d, 0x76, 0x9a, 0xab, 0xbe, 0x0e, 0x3e, 0x74, 0x80, 0xc0, 0x66, 0x80,
	0x93, 0x2c, 0xe3, 0x06, 0x2c, 0x2b, 0x2d, 0x24, 0x1d, 0xa0, 0x87, 0x80, 0x4d, 0xa9, 0x78, 0xd1,
	0x51, 0x76, 0xe0, 0x2c, 0x76, 0x98, 0xb2, 0x6b, 0xe4, 0xb5, 0x33, 0x0e, 0x77, 0xc7, 0xee, 0x0f,
	0xa1, 0x62, 0xdf, 0xb1, 0xe2, 0x45, 0x7b, 0x04, 0x61, 0x0f, 0x36, 0xa7, 0xc6, 0x8d, 0x34, 0x46,
	0xf9, 0x44, 0x50, 0x19, 0x77, 0x51, 0xd3, 0x64, 0x48, 0x08, 0x2c, 0x72, 0x9a, 0xa2, 0x9d, 0x4e,
	0x10, 0xd9, 0xff, 0x64, 0x0d, 0x0a, 0x3c, 0x4b, 0x0f, 0x51, 0xda, 0xa1, 0xe4, 0x22, 0x1f, 0x85,
	0x2d, 0xa8, 0xbd, 0x18, 0x9f, 0xc3, 0x22, 0xfc, 0x90, 0xa1, 0xd2, 0x64, 0x1d, 0x8a, 0x76, 0xcc,
	0x49, 0xec, 0x29, 0x05, 0x13, 0xf6, 0xe2, 0xf0, 0x35, 0x6c, 0x44, 0x38, 0x48, 0x94, 0x46, 0xf9,
	0xf7, 0x55, 0xe6, 0xc5, 0xd9, 0x30, 0x33, 0x45, 0x7d, 0xfb, 0x64, 0x0b, 0xee, 0xc5, 0xbd, 0xb6,
	0x47, 0x53, 0x0c, 0x3f, 0x43, 0x63, 0x1e, 0xf8, 0xfc, 0xda, 0xb1, 0x61, 0x82, 0x5c, 0xf7, 0x8f,
	0x71, 0xec, 0xe1, 0x81, 0x53, 0x9e, 0xe1, 0x98, 0xdc, 0x86, 0xaa, 0xb7, 0x99, 0x92, 0x7d, 0x86,
	0x52, 0xfb, 0x16, 0xcb, 0x4e, 0xee, 0x28, 0xd9, 0x41, 0x69, 0x1f, 0x90, 0x51, 0xe7, 0xe7, 0xdd,
	0x03, 0x32, 0x6a, 0x8c, 0xdd, 0x08, 0xa0, 0xdb, 0x39, 0xd0, 0x12, 0x69, 0x8a, 0x92, 0x74, 0xa1,
	0x72, 0x80, 0xf2, 0xc4, 0x2c, 0x85, 0x51, 0xc8, 0xda, 0x6f, 0x4b, 0xe3, 0x33, 0x1b, 0x17, 0xe8,
	0xe1, 0x7f, 0xcd, 0xdc, 0xbd, 0xdc, 0xee, 0xb7, 0x45, 0x58, 0xea, 0x76, 0x1e, 0xef, 0xf7, 0xc8,
	0x1b, 0x58, 0x99, 0x5d, 0x4f, 0x52, 0x9b, 0xad, 0x7c, 0x9a, 0x8e, 0xf4, 0xb8, 0xb1, 0xd3, 0x9a,
	0x7c, 0x04, 0x5a, 0xf3, 0xd7, 0x39, 0xfc, 0xff, 0xcb, 0x8f, 0x9f, 0x5f, 0x17, 0x80, 0x94, 0xda,
	0x31, 0x6b, 0x0f, 0x0d, 0xe9, 0x2d, 0x94, 0xa7, 0xf6, 0x74, 0x3e, 0x78, 0x6b, 0x0a, 0x3c, 0x67,
	0xa9, 0xc3, 0x75, 0x4b, 0xbd, 0x42, 0xaa, 0x86, 0xea, 0x6f, 0x5a, 0x62, 0x68, 0x9f, 0x80, 0xfc,
	0x39, 0x14, 0x72, 0x73, 0x0a, 0x77, 0xe1, 0x65, 0x68, 0xdc, 0xba, 0x24, 0x6b, 0xb6, 0x77, 0x58,
	0x31, 0xbd, 0xa5, 0xcf, 0x7b, 0x94, 0xbb, 0x4b, 0x34, 0x54, 0x23, 0x54, 0xa8, 0xff, 0x55, 0xe3,
	0x55, 0xdb, 0x78, 0x25, 0x0c, 0x5c, 0x63, 0x85, 0xda, 0x74, 0x7d, 0x07, 0x95, 0xe9, 0x7d, 0x20,
	0xd3, 0x47, 0x37, 0x67, 0x51, 0x1a, 0x97, 0x7c, 0x4f, 0x67, 0x07, 0x96, 0x8e, 0x63, 0x76, 0x58,
	0xb0, 0x99, 0x0f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x0c, 0x88, 0x2c, 0x08, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DCStreamerClient is the client API for DCStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DCStreamerClient interface {
	ServerStream(ctx context.Context, opts ...grpc.CallOption) (DCStreamer_ServerStreamClient, error)
}

type dCStreamerClient struct {
	cc *grpc.ClientConn
}

func NewDCStreamerClient(cc *grpc.ClientConn) DCStreamerClient {
	return &dCStreamerClient{cc}
}

func (c *dCStreamerClient) ServerStream(ctx context.Context, opts ...grpc.CallOption) (DCStreamer_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DCStreamer_serviceDesc.Streams[0], "/gwexdcmgr.DCStreamer/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dCStreamerServerStreamClient{stream}
	return x, nil
}

type DCStreamer_ServerStreamClient interface {
	Send(*common.DCStream) error
	Recv() (*common.DCStream, error)
	grpc.ClientStream
}

type dCStreamerServerStreamClient struct {
	grpc.ClientStream
}

func (x *dCStreamerServerStreamClient) Send(m *common.DCStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dCStreamerServerStreamClient) Recv() (*common.DCStream, error) {
	m := new(common.DCStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DCStreamerServer is the server API for DCStreamer service.
type DCStreamerServer interface {
	ServerStream(DCStreamer_ServerStreamServer) error
}

// UnimplementedDCStreamerServer can be embedded to have forward compatible implementations.
type UnimplementedDCStreamerServer struct {
}

func (*UnimplementedDCStreamerServer) ServerStream(srv DCStreamer_ServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}

func RegisterDCStreamerServer(s *grpc.Server, srv DCStreamerServer) {
	s.RegisterService(&_DCStreamer_serviceDesc, srv)
}

func _DCStreamer_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DCStreamerServer).ServerStream(&dCStreamerServerStreamServer{stream})
}

type DCStreamer_ServerStreamServer interface {
	Send(*common.DCStream) error
	Recv() (*common.DCStream, error)
	grpc.ServerStream
}

type dCStreamerServerStreamServer struct {
	grpc.ServerStream
}

func (x *dCStreamerServerStreamServer) Send(m *common.DCStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dCStreamerServerStreamServer) Recv() (*common.DCStream, error) {
	m := new(common.DCStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DCStreamer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gwexdcmgr.DCStreamer",
	HandlerType: (*DCStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _DCStreamer_ServerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dcmgr/v1/dcmgr.proto",
}

// DCAPIClient is the client API for DCAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DCAPIClient interface {
	DataCenterList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DataCenterListResponse, error)
	NetworkInfo(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NetworkInfoResponse, error)
	RegisterDataCenter(ctx context.Context, in *RegisterDataCenterRequest, opts ...grpc.CallOption) (*RegisterDataCenterResponse, error)
	ResetDataCenter(ctx context.Context, in *RegisterDataCenterRequest, opts ...grpc.CallOption) (*RegisterDataCenterResponse, error)
	MyDataCenter(ctx context.Context, in *MyDataCenterRequest, opts ...grpc.CallOption) (*common.DataCenterStatus, error)
}

type dCAPIClient struct {
	cc *grpc.ClientConn
}

func NewDCAPIClient(cc *grpc.ClientConn) DCAPIClient {
	return &dCAPIClient{cc}
}

func (c *dCAPIClient) DataCenterList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DataCenterListResponse, error) {
	out := new(DataCenterListResponse)
	err := c.cc.Invoke(ctx, "/gwexdcmgr.DCAPI/DataCenterList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCAPIClient) NetworkInfo(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NetworkInfoResponse, error) {
	out := new(NetworkInfoResponse)
	err := c.cc.Invoke(ctx, "/gwexdcmgr.DCAPI/NetworkInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCAPIClient) RegisterDataCenter(ctx context.Context, in *RegisterDataCenterRequest, opts ...grpc.CallOption) (*RegisterDataCenterResponse, error) {
	out := new(RegisterDataCenterResponse)
	err := c.cc.Invoke(ctx, "/gwexdcmgr.DCAPI/RegisterDataCenter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCAPIClient) ResetDataCenter(ctx context.Context, in *RegisterDataCenterRequest, opts ...grpc.CallOption) (*RegisterDataCenterResponse, error) {
	out := new(RegisterDataCenterResponse)
	err := c.cc.Invoke(ctx, "/gwexdcmgr.DCAPI/ResetDataCenter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCAPIClient) MyDataCenter(ctx context.Context, in *MyDataCenterRequest, opts ...grpc.CallOption) (*common.DataCenterStatus, error) {
	out := new(common.DataCenterStatus)
	err := c.cc.Invoke(ctx, "/gwexdcmgr.DCAPI/MyDataCenter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DCAPIServer is the server API for DCAPI service.
type DCAPIServer interface {
	DataCenterList(context.Context, *common.Empty) (*DataCenterListResponse, error)
	NetworkInfo(context.Context, *common.Empty) (*NetworkInfoResponse, error)
	RegisterDataCenter(context.Context, *RegisterDataCenterRequest) (*RegisterDataCenterResponse, error)
	ResetDataCenter(context.Context, *RegisterDataCenterRequest) (*RegisterDataCenterResponse, error)
	MyDataCenter(context.Context, *MyDataCenterRequest) (*common.DataCenterStatus, error)
}

// UnimplementedDCAPIServer can be embedded to have forward compatible implementations.
type UnimplementedDCAPIServer struct {
}

func (*UnimplementedDCAPIServer) DataCenterList(ctx context.Context, req *common.Empty) (*DataCenterListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataCenterList not implemented")
}
func (*UnimplementedDCAPIServer) NetworkInfo(ctx context.Context, req *common.Empty) (*NetworkInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkInfo not implemented")
}
func (*UnimplementedDCAPIServer) RegisterDataCenter(ctx context.Context, req *RegisterDataCenterRequest) (*RegisterDataCenterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDataCenter not implemented")
}
func (*UnimplementedDCAPIServer) ResetDataCenter(ctx context.Context, req *RegisterDataCenterRequest) (*RegisterDataCenterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetDataCenter not implemented")
}
func (*UnimplementedDCAPIServer) MyDataCenter(ctx context.Context, req *MyDataCenterRequest) (*common.DataCenterStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyDataCenter not implemented")
}

func RegisterDCAPIServer(s *grpc.Server, srv DCAPIServer) {
	s.RegisterService(&_DCAPI_serviceDesc, srv)
}

func _DCAPI_DataCenterList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCAPIServer).DataCenterList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwexdcmgr.DCAPI/DataCenterList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCAPIServer).DataCenterList(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCAPI_NetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCAPIServer).NetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwexdcmgr.DCAPI/NetworkInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCAPIServer).NetworkInfo(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCAPI_RegisterDataCenter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDataCenterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCAPIServer).RegisterDataCenter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwexdcmgr.DCAPI/RegisterDataCenter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCAPIServer).RegisterDataCenter(ctx, req.(*RegisterDataCenterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCAPI_ResetDataCenter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDataCenterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCAPIServer).ResetDataCenter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwexdcmgr.DCAPI/ResetDataCenter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCAPIServer).ResetDataCenter(ctx, req.(*RegisterDataCenterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCAPI_MyDataCenter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyDataCenterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCAPIServer).MyDataCenter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwexdcmgr.DCAPI/MyDataCenter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCAPIServer).MyDataCenter(ctx, req.(*MyDataCenterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DCAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gwexdcmgr.DCAPI",
	HandlerType: (*DCAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataCenterList",
			Handler:    _DCAPI_DataCenterList_Handler,
		},
		{
			MethodName: "NetworkInfo",
			Handler:    _DCAPI_NetworkInfo_Handler,
		},
		{
			MethodName: "RegisterDataCenter",
			Handler:    _DCAPI_RegisterDataCenter_Handler,
		},
		{
			MethodName: "ResetDataCenter",
			Handler:    _DCAPI_ResetDataCenter_Handler,
		},
		{
			MethodName: "MyDataCenter",
			Handler:    _DCAPI_MyDataCenter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dcmgr/v1/dcmgr.proto",
}
