// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify/v1/transaction.proto

package notify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionState int32

const (
	TransactionState_TransactionUnknown     TransactionState = 0
	TransactionState_TransactionUnConfirmed TransactionState = 1
	TransactionState_TransactionPending     TransactionState = 2
	TransactionState_TransactionConfirmed   TransactionState = 3
)

var TransactionState_name = map[int32]string{
	0: "TransactionUnknown",
	1: "TransactionUnConfirmed",
	2: "TransactionPending",
	3: "TransactionConfirmed",
}

var TransactionState_value = map[string]int32{
	"TransactionUnknown":     0,
	"TransactionUnConfirmed": 1,
	"TransactionPending":     2,
	"TransactionConfirmed":   3,
}

func (x TransactionState) String() string {
	return proto.EnumName(TransactionState_name, int32(x))
}

func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b8d9130bd3f234c, []int{0}
}

type TransactionStateChangeEvent struct {
	FromAccountAddress   string           `protobuf:"bytes,1,opt,name=fromAccountAddress,proto3" json:"fromAccountAddress,omitempty"`
	ToAccountAddress     string           `protobuf:"bytes,2,opt,name=toAccountAddress,proto3" json:"toAccountAddress,omitempty"`
	TxHash               string           `protobuf:"bytes,3,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Amount               string           `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ConfirmedBlockHeight uint64           `protobuf:"varint,5,opt,name=confirmedBlockHeight,proto3" json:"confirmedBlockHeight,omitempty"`
	TxState              TransactionState `protobuf:"varint,6,opt,name=txState,proto3,enum=notify.TransactionState" json:"txState,omitempty"`
	Memo                 string           `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TransactionStateChangeEvent) Reset()         { *m = TransactionStateChangeEvent{} }
func (m *TransactionStateChangeEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionStateChangeEvent) ProtoMessage()    {}
func (*TransactionStateChangeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8d9130bd3f234c, []int{0}
}

func (m *TransactionStateChangeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionStateChangeEvent.Unmarshal(m, b)
}
func (m *TransactionStateChangeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionStateChangeEvent.Marshal(b, m, deterministic)
}
func (m *TransactionStateChangeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionStateChangeEvent.Merge(m, src)
}
func (m *TransactionStateChangeEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionStateChangeEvent.Size(m)
}
func (m *TransactionStateChangeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionStateChangeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionStateChangeEvent proto.InternalMessageInfo

func (m *TransactionStateChangeEvent) GetFromAccountAddress() string {
	if m != nil {
		return m.FromAccountAddress
	}
	return ""
}

func (m *TransactionStateChangeEvent) GetToAccountAddress() string {
	if m != nil {
		return m.ToAccountAddress
	}
	return ""
}

func (m *TransactionStateChangeEvent) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TransactionStateChangeEvent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransactionStateChangeEvent) GetConfirmedBlockHeight() uint64 {
	if m != nil {
		return m.ConfirmedBlockHeight
	}
	return 0
}

func (m *TransactionStateChangeEvent) GetTxState() TransactionState {
	if m != nil {
		return m.TxState
	}
	return TransactionState_TransactionUnknown
}

func (m *TransactionStateChangeEvent) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func init() {
	proto.RegisterEnum("notify.TransactionState", TransactionState_name, TransactionState_value)
	proto.RegisterType((*TransactionStateChangeEvent)(nil), "notify.TransactionStateChangeEvent")
}

func init() { proto.RegisterFile("notify/v1/transaction.proto", fileDescriptor_3b8d9130bd3f234c) }

var fileDescriptor_3b8d9130bd3f234c = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdd, 0x4a, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0xb4, 0xfd, 0x52, 0x9c, 0x03, 0x09, 0x43, 0x09, 0x8b, 0x3d, 0x09, 0x1e, 0x85,
	0x1e, 0xa4, 0x18, 0xaf, 0xa0, 0x16, 0xa1, 0x87, 0x12, 0xf5, 0x02, 0xd6, 0x64, 0xf3, 0x43, 0xcd,
	0x8c, 0x24, 0x63, 0x8d, 0x17, 0xe4, 0x7d, 0x4a, 0x37, 0x96, 0xd6, 0xd8, 0xb3, 0x9d, 0xe7, 0x7d,
	0x86, 0xdd, 0x97, 0x85, 0x39, 0xb1, 0x54, 0xf9, 0xe7, 0x72, 0x77, 0xb3, 0x94, 0x46, 0x53, 0xab,
	0x53, 0xa9, 0x98, 0xa2, 0xb7, 0x86, 0x85, 0xd1, 0xed, 0xc3, 0xeb, 0xaf, 0x11, 0xcc, 0x9f, 0x8e,
	0xe9, 0xa3, 0x68, 0x31, 0xeb, 0x52, 0x53, 0x61, 0xee, 0x77, 0x86, 0x04, 0x23, 0xc0, 0xbc, 0xe1,
	0x7a, 0x95, 0xa6, 0xfc, 0x4e, 0xb2, 0xca, 0xb2, 0xc6, 0xb4, 0xad, 0x72, 0x02, 0x27, 0xbc, 0x48,
	0xce, 0x24, 0xb8, 0x00, 0x4f, 0x78, 0x60, 0x8f, 0xac, 0xfd, 0x87, 0xa3, 0x0f, 0xae, 0x74, 0x1b,
	0xdd, 0x96, 0x6a, 0x6c, 0x8d, 0x9f, 0x69, 0xcf, 0x75, 0xbd, 0x17, 0xd5, 0xa4, 0xe7, 0xfd, 0x84,
	0x31, 0xcc, 0x52, 0xa6, 0xbc, 0x6a, 0x6a, 0x93, 0xdd, 0xbd, 0x72, 0xba, 0xdd, 0x98, 0xaa, 0x28,
	0x45, 0xfd, 0x0f, 0x9c, 0x70, 0x92, 0x9c, 0xcd, 0x30, 0x86, 0xa9, 0x74, 0xb6, 0x95, 0x72, 0x03,
	0x27, 0xbc, 0x8c, 0x55, 0xd4, 0x37, 0x8f, 0x86, 0xad, 0x93, 0x83, 0x88, 0x08, 0x93, 0xda, 0xd4,
	0xac, 0xa6, 0xf6, 0x76, 0x7b, 0x5e, 0x74, 0xe0, 0x0d, 0x17, 0xd0, 0x07, 0x3c, 0x61, 0xcf, 0xb4,
	0x25, 0xfe, 0x20, 0xef, 0x1f, 0x5e, 0x81, 0xff, 0x8b, 0xaf, 0x0f, 0x0f, 0xf3, 0x9c, 0xc1, 0xce,
	0x83, 0xa1, 0xac, 0xa2, 0xc2, 0x1b, 0xa1, 0x82, 0xd9, 0x09, 0x3f, 0x6e, 0x8c, 0x5f, 0x5c, 0xfb,
	0x61, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x23, 0xe5, 0x60, 0xcf, 0x01, 0x00, 0x00,
}
